# Possible options are 'grub', 'sb-shim' and 'systemd-boot'.
efiBootLoader: "grub"

kernelSearchPath: "/usr/lib/modules"
#kernelName: "vmlinuz"
kernelPattern: "^vmlinuz.*"
timeout: "10"

# systemd-boot and refind support custom kernel params
kernelParams: [ "nvme_load=YES","nowatchdog","quiet" ]
refindKernelList: [ "linux","linux-lts","linux-zen","linux-hardened" ]
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
efiBootloaderId: "parchlinux"

installEFIFallback: false

loaderEntries:
  - "timeout 5"
  - "console-mode auto"
  - "reboot-for-bitlocker 1"

installHybridGRUB: false
