# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# partition handling.
---
efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    1024MiB
    minimumSize:        500MiB
    label:              "EFI"


# set to 512M for best compatinbility for buggy old EFI firmware
#efiSystemPartitionSize:     512M

userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Up to 4GB
    - suspend   # At least main memory size
    - file      # To swap file instead of partition


drawNestedPartitions:   false

alwaysShowPartitionLabels: true

initialPartitioningChoice: none

initialSwapChoice: none

defaultFileSystemType:  "ext4"

showNotEncryptedBootMessage:   false

luksGeneration: luks1


availableFileSystemTypes:  ["ext4","f2fs","xfs","btrfs"]

partitionLayout:
    - name: "ParchLinux"
      filesystem: "unknown"
      mountPoint: "/"
      size: 100%
