# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# shellprocess_copy_kernel.conf
# copy kernel, initramfs, and ucode to target boot

---
dontChroot: true
timeout: 300
script:
  - "mkdir -p ${ROOT}/boot"
  - "cp /run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux ${ROOT}/boot/vmlinuz-linux"
  - "-cp /run/archiso/bootmnt/arch/boot/x86_64/initramfs-linux.img ${ROOT}/boot/initramfs-linux.img"
  - "-cp /run/archiso/bootmnt/arch/boot/amd-ucode.img ${ROOT}/boot/amd-ucode.img"
  - "-cp /run/archiso/bootmnt/arch/boot/intel-ucode.img ${ROOT}/boot/intel-ucode.img"
  - "-cp -n /boot/amd-ucode.img ${ROOT}/boot/amd-ucode.img"
  - "-cp -n /boot/intel-ucode.img ${ROOT}/boot/intel-ucode.img"
