# Configuration for the welcomeq module, based on Parch welcome settings.
---
qmlSearch: both

showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false
showDonateUrl:          https://daramet.com/parchlinux

requirements:
    requiredStorage:    5.5
    requiredRam:        1.0
    internetCheckUrl:   https://parchlinux.com

    check:
        - storage
        - ram
        - power
        - root
        - screen
    required:
        - storage
        - ram
